### PR TITLE
Added Solution to LinearSearch.cpp

### PR DESCRIPTION
**Pull request by hrishikeshmohan23**
Added a cpp file for Linear Search in C++

### CODE REVIEW

**Review by bishwobista — CHANGES_REQUESTED** [review]
Please don't change other files.

**Comment by hrishikeshmohan23** [comment]
I think someone has edited that file in main. I was not able to discard the changes in remote. Let me check.

**Comment by hrishikeshmohan23** [comment]
The updates have been made

**Comment by bishwobista** [comment]
Ahh alright

**Review by bishwobista — APPROVED** [review]
Thank you for your contribution. Happy hacktoberfest.

**Pull request merged**
