### PR TITLE
Create BinarySearch.java

### PR DESCRIPTION
**Pull request by idrismusa4**
solved #59 by adding code for binary search in java

### CODE REVIEW

**Review by bishwobista — APPROVED** [review]
Thank you for your contribution. If you have any other problems to add, raise an issue.

**Comment by idrismusa4** [comment]
Thanks

**Comment by bishwobista** [comment]
> Thanks

Welcome, happy hacktoberfest.

**Comment by idrismusa4** [comment]
@bishwobista can you kindly add the "hacktoberfest-accepted" label or "hacktoberfest" to the pull request

**Comment by bishwobista** [comment]
> @bishwobista can you kindly add the "hacktoberfest-accepted" label or "hacktoberfest" to the pull request

My bad, I will add it rn. The repo has hacktoberfest and hacktoberfest-accepted titles so its all good anyway.

**Comment by idrismusa4** [comment]
Thanks

**Pull request merged**
